version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  modules-download-mode: readonly

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustruct
    - forbidigo
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godot
    - godox
    - ireturn
    - lll
    - maintidx
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - noinlineerr
    - paralleltest
    - tagalign
    - tagliatelle
    - unparam
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
    - wsl_v5

  settings:
    usetesting:
      context-background: true
      context-todo: true

    errcheck:
      check-type-assertions: true

    exhaustive:
      default-signifies-exhaustive: true

    gocritic:
      disabled-checks:
        - appendAssign

    gosec:
      excludes:
        - G104

    govet:
      enable-all: true
      disable:
        - fieldalignment

    misspell:
      locale: US

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
        - name: redefines-builtin-id

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
      - path: _test\.go
        text: "dot-imports"

formatters:
  enable:
    - gofmt
    - goimports
